/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote;

import java.util.Random;

public class App {
    public String getGreeting() {

        return "Java Quotes";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        FileIO.getOneQuote();
        getAllQuotes();
        getSize();
    }

    public static int getSize(){
        return FileIO.readFile().length;
    }

    public static Quote[] getAllQuotes(){
        Quote[] quotesList = FileIO.readFile();
        return quotesList;
    }

}
