/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote;

import java.util.Random;

public class App {
    public String getGreeting() {

        return "Java Quotes";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        System.out.println(getRandom());

        System.out.println(getAllQuotes());

        System.out.println(getSize());
    }

    public static int getSize(){
        return FileIO.readFile().length;
    }

    public static Quote[] getAllQuotes(){
        System.out.println("All Quotes");

        Quote[] quotesList = FileIO.readFile();

//        for(Quote line: FileIO.readFile()){
//            System.out.println(line);
//        }

        return quotesList;

    }

    public static Quote getRandom(){
        Quote[] quoteList = FileIO.readFile();
//        System.out.println("Today's One random quote");
        int random = new Random().nextInt(quoteList.length);
        return quoteList[random];
    }





}
