/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote;

import org.junit.Before;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;
import java.util.Queue;

import static org.junit.Assert.*;

public class AppTest {

    @Before
    public void setup(){
        FileIO fileIO = new FileIO();
        App.getOneQuote(fileIO.readFile());
    }

    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    // Test getRonSwanson method no exception
    @Test
    public void testGetRonSwanson(){
        FileIO fileIO = new FileIO();
        Quote quote = fileIO.getRonSwanson();
        assertTrue("Should return a quote from Ron Swanson API", quote.toString().contains("Ron Swanson"));
    }

    // Test add to json returns true when added to the file
    @Test
    public void testAddToJson(){
        FileIO fileIO = new FileIO();
        Quote quote = new Quote(new String[]{}, "Hello Kitty", "300", "Meow Meow Meow");

        assertTrue("Returns true when quote is added to the file", fileIO.addToJson(quote));

    }


}
