/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;
import java.util.Queue;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void getSize() {
        assertEquals("Should be 138 quotes", 138, App.getSize());
    }

    @Test
    public void getAllQuotes() {
        List<Quote> quoteList = Arrays.asList(App.getAllQuotes());

        Quote getAuthor = quoteList.get(136);
        System.out.println(getAuthor);

        assertTrue("Should contain Tove Jannson ", quoteList.contains(getAuthor));


    }

}
