/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void getSize() {
        assertEquals("Should be 138 quotes", 138, App.getSize());
    }

    @Test
    public void getAllQuotes() {
        List<Quote> quoteList = Arrays.asList(App.getAllQuotes());

        for(Quote quote: quoteList){
            System.out.println(quoteList);
        }

        assertTrue("Should contain ", quoteList.contains("Quote{tags=[], author='Tove Jansson', likes='4 likes', text=' “Seine Gedanken oder plötzlichen Wünsche flogen wie die Laune des Meeres über das Wasser, mal hierhin, mal dorthin, und er lebte ununterbrochen in einer stillen Spannung.” '}\n"));
    }

    @Test
    public void getRandom() {
    }
}
